export const container: string;
export const iWin: string;
export const rotate: string;
export const title: string;
export const resolution: string;
export const text: string;
export const ryanImage: string;
export const navigation: string;
export const logo: string;